module.exports = {
    ACCESS_KEY: process.env.ACCESS_KEY,
    REFRESH_KEY: process.env.REFRESH_KEY,
    DB_DIALECT: process.env.DB_DIALECT,
    DB_NAME: process.env.DB_NAME,
    DB_USERNAME: process.env.DB_USERNAME,
    DB_PASSWORD: process.env.DB_PASSWORD,
    APP_PORT: process.env.APP_PORT,
    HOST: process.env.HOST,
    USER_TABLE: process.env.USER_TABLE,
    USER_MODEL: process.env.USER_MODEL,
    CAR_TABLE: process.env.CAR_TABLE,
    CAR_MODEL: process.env.CAR_MODEL,
    OAUTH_TABLE: process.env.OAUTH_TABLE,
    OAUTH_MODEL: process.env.OAUTH_MODEL,
    DOCUMENT_TABLE: process.env.DOCUMENT_TABLE,
    DOCUMENT_MODEL: process.env.DOCUMENT_MODEL,
    FOREIGN_USER_ID: process.env.FOREIGN_USER_ID,
    FOREIGN_CAR_ID: process.env.FOREIGN_CAR_ID,
    KEY_ID: process.env.KEY_ID,
    ACCESS_EXPIRATION: process.env.ACCESS_EXPIRATION,
    REFRESH_EXPIRATION: process.env.REFRESH_EXPIRATION,
    EMAIL_SERVICE: process.env.EMAIL_SERVICE,
    EMAIL_USER: process.env.EMAIL_USER,
    EMAIL_PASS: process.env.EMAIL_PASS,
};
